title: Autumn Cottage Life
baseurl: /
permalink: '/:title/'
description: A minimal blogging theme for Stackbit
palette: yellow
header:
  type: header
  template: header
  title: Fjord
  tagline: Minimal and clean blog theme
  logo_img: /images/Trans-Asset 1.png
  background_img: /images/127772807_701905537135127_3819956554134411547_n.jpg
  has_nav: true
  nav_links:
    - type: action
      template: action
      label: Blog
      url: /
      style: link
      icon_class: ''
      new_window: false
    - type: action
      template: action
      label: My Story
      url: /about
      style: link
      icon_class: ''
      new_window: false
    - type: action
      template: action
      label: About The Cottage
      url: /style-guide
      style: link
      icon_class: ''
      new_window: false
    - type: action
      template: action
      label: Get In Touch
      url: /contact
      style: link
      icon_class: ''
      new_window: false
  has_social: true
  social_links:
    - type: action
      template: action
      label: Instagram
      url: 'https://www.instagram.com/autumncottagelife/'
      style: icon
      icon_class: fa-instagram
      new_window: true
    - type: action
      template: action
      label: Facebook
      url: 'https://www.facebook.com/autumncottagelife'
      style: icon
      icon_class: fa-facebook
      new_window: true
    - type: action
      template: action
      label: Pinterest
      url: 'https://www.pinterest.co.uk/autumncottagelife/_created/'
      style: icon
      icon_class: fa-pinterest
      new_window: true
footer:
  type: footer
  template: footer
  content: Autumn Cottage Life &copy; All rights reserved.
  links:
    - type: action
      template: action
      label: Created by Ninja Web Services.
      url: 'https://www.ninjawebservices.com'
      style: link
      new_window: true
      icon_class: ''
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
collections:
  posts:
    permalink: '/posts/:title/'
